vim.g.gruvbox_bold = 1
vim.g.gruvbox_italic = 1
vim.g.gruvbox_transparent_bg = 1
vim.g.gruvbox_underline = 0
vim.g.gruvbox_undercurl = 0
vim.g.gruvbox_termcolors = 256 -- 16, 256
vim.g.gruvbox_contrast_dark = "hard"  -- soft, medium, hard
vim.g.gruvbox_contrast_light = "hard"
vim.g.gruvbox_hls_cursor = "orange"
vim.g.gruvbox_number_column = "none"
vim.g.gruvbox_sign_column = "none"
vim.g.gruvbox_color_column = "none"
vim.g.gruvbox_vert_split = "none"
vim.g.gruvbox_italicize_comments = 1
vim.g.gruvbox_italicize_strings = 1
vim.g.gruvbox_invert_selection = 0
vim.g.gruvbox_invert_signs = 0
vim.g.gruvbox_invert_indent_guides = 0
vim.g.gruvbox_invert_tabline = 0
vim.g.gruvbox_improved_strings = 1
vim.g.gruvbox_improved_warnings = 1
vim.g.gruvbox_guisp_fallback  = 'NONE'
